### ISSUE TITLE
Add support for scheduled maintenance

### ISSUE THREAD

**Issue by ericgriffis** [NYULibraries/statuspage-embed#12]
Statuspage returns "scheduled_maintenances" as a separate array from "incidents" as seen in [this example](https://gist.github.com/ericgriffis/453af8318e1f291e2be3119369e45552). We want to display valid scheduled maintenance in this array using [the same logic as implemented in status jockey](https://github.com/NYULibraries/library.nyu.edu/wiki/Statuspage.io-site-alerts).

**Comment by laurxnemeth** [comment]
In progress, just leaving the link to the logic used in [library.nyu.edu](https://github.com/NYULibraries/library.nyu.edu/blob/572e8e5f1fb58a9f5afaeba8781b237a06ffbb53/assets/js/src/components/alert/index.js)

**Comment by laurxnemeth** [comment]
@ericgriffis pretty much done for supporting scheduled maintenance, going to look at it again tomorrow to see if I can refactor for neatness but otherwise it has a [branch](https://github.com/NYULibraries/statuspage-embed/tree/fix/scheduledmaintenance). check it out on your own time and let me know if you think it needs any changes/you have any advice.
